name 'izbinden_test_cookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures izbinden_test_cookbook'
long_description 'Installs/Configures izbinden_test_cookbook'
version '0.1.0'

issues_url 'https://jira.marchex.com'
source_url 'https://github.marchex.com/marchex-chef/izbinden_test_cookbook'
