source 'https://rubygems.org'

gem 'mixlib-install'
gem 'mixlib-shellout'
gem 'tty-prompt'
gem 'chef-api'
gem 'octokit', '>= 4.6.0'
gem 'chef'
gem 'chef-dk'
gem 'json'
gem 'method_source'
gem 'addressable', '~> 2.5.0'
gem 'chef-provisioning'
gem 'cookbook-omnifetch'
gem 'paint'
gem 'solve'
gem 'safe_yaml'

group :test do
  gem 'rspec'
end
gem 'parallel'
gem 'pry'
gem 'rainbow'
gem 'sslshake'
gem 'train'
gem 'inspec'
