name             'marchex-chef-generator'
maintainer       'Marchex, Inc.'
maintainer_email 'tools@marchex.com'
license          'Apache 2 License'
description      'Generates Chef code for Chef DK'
long_description 'Generates Chef code for Chef DK'
version          '1.0.0'
