source 'https://rubygems.org'

gem 'rake'
gem 'berkshelf'
gem 'marchex_helpers', '>= 0.1.21', source: 'http://rubygems.sea.marchex.com/'

group :development do
  gem 'foodcritic'
  gem 'rubocop'
  gem 'chefspec'
end

group :integration do
  gem 'kitchen-ec2'
  gem 'kitchen-inspec'
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
end
