# require "bundler/setup"

task :default => [:list]

desc "List all the tasks."
task :list do
    puts "Tasks: \n- #{Rake::Task.tasks.join("\n- ")}"
end

desc "Check for required dependencies."
task :check do
  sh "bundle check"
end

desc "Run chefspec tests."
task :chefspec do
    sh "rspec spec"
end

desc "Run kitchen tests."
task :kitchen do
    sh "kitchen test"
end

desc "Run foodcritic."
task :foodcritic do
    sh "foodcritic ."  # runs all built-in foodcritic rules
    sh "foodcritic . -G -t marchex_base" # marchex-specific rules
end

desc "Run rubocop."
task :rubocop do
    sh "rubocop ."
end

desc "Run validation tests."
task :lint do
  Rake::Task[:foodcritic].execute
  Rake::Task[:rubocop].execute
end

desc "Run unit tests."
task :unit do
  Rake::Task[:lint].execute
  Rake::Task[:chefspec].execute
end

desc "Run integration tests."
task :integration do
  Rake::Task[:chefspec].execute
  Rake::Task[:kitchen].execute
end

desc "Run delivery verify tests."
task :dverify do
  sh "delivery job -l verify 'unit lint syntax'"
end

desc "Run delivery verify tests."
task :dkitchen do
  sh "delivery job -l acceptance functional"
end

desc "Run delivery verify tests."
task :delivery do
  Rake::Task[:dverify].execute
  Rake::Task[:dkitchen].execute
end
